
# .travis.yml
# Based on https://github.com/micropython/micropython/blob/master/.travis.yml
#
# TODO: Env matrix with different MicroPython versions.

sudo: required
dist: trusty
language: c
compiler:
  - gcc

install:
  - sudo apt-get update || true
  - sudo apt-get install -y build-essential libreadline-dev libffi-dev git python pkgconf
  - git clone --recurse-submodules https://github.com/micropython/micropython.git /tmp/micropython
  - make -C /tmp/micropython/unix axtls
  - make -C /tmp/micropython/unix
  - /tmp/micropython/unix/micropython -m upip install micropython-upip
  - /tmp/micropython/unix/micropython -m upip install micropython-copy \
                                                      micropython-binascii \
                                                      micropython-struct \
                                                      micropython-unittest \
                                                      micropython-types

script:
  - /tmp/micropython/unix/micropython test/test_bitstore.py
  - /tmp/micropython/unix/micropython test/test_bits.py
